project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  sidebar:
    style: "docked"
    search: false
    contents:
      - href: index.qmd
        text: Home
      - labs/02/Lab2WriteUp.qmd
      - labs/03/Lab3WriteUp.qmd
      - labs/04/Lab4WriteUp.qmd
      - labs/04/Menu.qmd
      - labs/05/Lab5WriteUp.qmd
      - labs/08/Lab8WriteUp.qmd
      - labs/10/Lab10WriteUp.qmd
      - labs/11/Lab11WriteUp.qmd
      - review/HypothesisTesting.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto


