{
  "hash": "050e31312238ecf3fe1351d434d7f2f5",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: Homework 2 -- k Sample Inference # Title of the document\n\n# Bibliography Details\nbibliography: HW2References.bib  # Name of bib file in the same folder \nbibliographystyle: apa            # Bibliography style\n\nexecute:               # Default settings for code blocks\n  warning: false       # Do not print warnings\n  message: false       # Do not print messages\n  size: \"scriptsize\"   # Set code size to script size\n\n# Below will do html by default. To render the entire project\n# Use the following code:\n# quarto::quarto_render(\"Lab10WriteUp.qmd\")\nformat:\n  pdf:        # Specify .pdf formatting options \n    documentclass: article     # Document Class\n    number-sections: true      # Number Sections\n    reference-section-title: \"References\" # Title for reference section\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables \n    geometry:\n      - top=0.75in\n      - left=0.75in\n      - bottom=0.75in\n      - right=0.75in\n  html:       # Specify HTML formatting options \n    number-sections: true      # Number Sections\n    code-fold: true            # Button to show code\n    code-line-numbers: true    # Line numbers printed in code\n    cap-location: top          # Captions at the top of tables and figures\nformat-links: [pdf]\n---\n\n \\normalsize\n\n\n::: {.cell}\n\n:::\n\n\n \\normalsize\n\n\n\n# Question 1: Why do we Correct for Multiple Comparisons?\nA student asked me what the point of correcting for multiple comparisons was. They made a two interesting points:\n\n1. They are different outcomes, so, unlike the coin flip example (where the coin is the same) it doesn't makes sense to combine them.\n2. If a manuscript presented three studies with $t$-tests, they don't correct for multiple comparisons across *those* tests.\n\nWhen we conduct all pairwise comparisons after an omnibus test like ANOVA, we are testing a single family of hypotheses to answer one overarching question (\"Which of these groups are different?\"). Every additional test provides another opportunity to commit a Type I error from random noise. Similar to the coin, the probability of making at least one false error across $J$ independent tests grows exponentially: $1 - (1 - \\alpha)^J$. Note that our pairwise comparisons are not independent, so it's slightly different.\n\nWe don't correct for inferences across separate studies because they typically test distinct hypotheses using independent samples. Our attempt to address the multiple comparisons problem is specifically confined to the issue of increased Type I error within a single decision-making context. If we don't, we can find ourselves in a $p$-hacking-like situation, where an investigator might search through many tests to find one $p < 0.05$ (a potential false discovery), rather than making decisions to best position themselves for finding a true discovery.\n\nHere, we will quickly demonstrate why we correct for the multiple comparisons problem when conducting several tests to answer the same question. \n\n## Part a\nComplete the following steps in $R=1000$ simulations.\n\n1. Simulate data for $k=5$ samples $n=30$ drawn from a standard Gaussian distribution.\n2. Use `pairwise.t.test(..., p.adjust.method=\"none\")` to compute unadjusted pairwise $t$-tests and record if any comparison yields statistically discernible support for a non-zero mean.\n3. Use `rstatix::tukey_hsd(...)` to compute the Tukey's HSD adjusted pairwise tests and record if any comparison yields statistically discernible support for a non-zero mean.\n\nIn the end, describe the Type I error rates.\n\n**Solution** \n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nR = 1000\nk = 5\nn = 30\nalpha = .05\nttest.false.pos = 0\nhsdtest.false.pos = 0\nfor (i in 1:R) {\n  dat = tibble(\n    labels = factor(rep(seq(from = 1,to = k,by = 1), each = 30)),\n    obs = rnorm(k * n)\n  )\n  ttest = pairwise.t.test(\n    x = dat$obs,\n    g = dat$labels,\n    p.adjust.method = \"none\",\n    alternative = \"two.sided\"\n    )\n  hsdtest = rstatix::tukey_hsd(dat, obs ~ labels)\n  \n  t.pvals = ttest$p.value\n  hsd.pvals = hsdtest$p.adj\n  ttest.false.pos = ttest.false.pos + length(t.pvals[!is.na(t.pvals) & t.pvals < alpha])\n  hsdtest.false.pos = hsdtest.false.pos + length(hsd.pvals[!is.na(hsd.pvals) & hsd.pvals < alpha])\n}\n(ttest.false.pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 535\n```\n\n\n:::\n\n```{.r .cell-code}\n(hsdtest.false.pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 78\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nSince for every test there are $\\binom{5}{2} = 10$ p-values, over $1000$ there are $10000$ total p-values calculated. By the definition of significance, we expect a false positive rate of $.05$, given our roughly $500$ false positives under the ttest, this is what we'd expect. Still, it's quite a few false positives, roughly $5 \\times$ what we get from the Tukey HSD.\n\n## Part b\nRedo the simulation, changing to adjust according to the false discovery rate `p.adjust.method=\"BH\"` and comment on the differences.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nttest.false.pos = 0\nhsdtest.false.pos = 0\nfor (i in 1:R) {\n  dat = tibble(\n    labels = factor(rep(seq(from = 1,to = k,by = 1), each = 30)),\n    obs = rnorm(k * n)\n  )\n  ttest = pairwise.t.test(\n    x = dat$obs,\n    g = dat$labels,\n    p.adjust.method = \"BH\",\n    alternative = \"two.sided\"\n    )\n  hsdtest = rstatix::tukey_hsd(dat, obs ~ labels)\n  \n  t.pvals = ttest$p.value\n  hsd.pvals = hsdtest$p.adj\n  ttest.false.pos = ttest.false.pos + length(t.pvals[!is.na(t.pvals) & t.pvals < alpha])\n  hsdtest.false.pos = hsdtest.false.pos + length(hsd.pvals[!is.na(hsd.pvals) & hsd.pvals < alpha])\n}\n(ttest.false.pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 110\n```\n\n\n:::\n\n```{.r .cell-code}\n(hsdtest.false.pos)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 83\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nAfter adjusting, the adjusted false positive rate is much more similar to the Tukey HSD.\n\n# Question 2: Power Analyses\nRevisit the MFAP4 study from class. \n\n## Part a\nAssume the researchers were targeting a moderate effect size of Cohen's $f = 0.25$, setting significance level $\\alpha = 0.05$ and desired power $1 - \\beta = 0.80$. Were they adequately powered?\n\n**Note**: The actual effect size is $f=0.55$, but researchers usually do not know that ahead of time and defaulted to moderate, instead of specifying a large effect.\n\nWhat is the required sample size per group ($n$) and the overall total sample size ($N$)? Write the `R` code using the `pwr` package to calculate this sample size. This package assumes all samples are of the same size so $N=nk$, where $k$ is the number of samples. Note that the best answers will have a corresponding graphical display.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk = 5\nsample.size = pwr::pwr.anova.test(\n    k = k,\n    n = NULL,\n    f = .25,\n    sig.level = .05,\n    power = .8\n    )\n(sample.size$n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 39.1534\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nYes, All samples in the group were larger than the minimum per group sample size of 40. The total minimum sample size is 200.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_plot = function(n,k,f,alpha) {\n  N   = k * n\n  df1 = k - 1\n  df2 = N - k\n  noncentrality = f^2 * N                      # noncentrality parameter (Cohen's f)\n  crit = qf(1 - alpha, df1, df2)     # critical F value\n\n  x = sort(c(seq(0, 15, length.out = 1000), crit))   # include crit so shading meets exactly\n  dat = data.frame(\n    x    = x,\n    null = df(x, df1, df2),\n    alt  = df(x, df1, df2, ncp = noncentrality)\n  )\n\n  low = subset(dat, x <= crit)\n  high = subset(dat, x >= crit)\n\n  ggplot(dat, aes(x)) +\n    geom_ribbon(data = low, aes(ymin = 0, ymax = alt,  fill = \"Type II Error\"), alpha = 0.7) +\n    geom_ribbon(data = high, aes(ymin = 0, ymax = alt,  fill = \"Power\"),         alpha = 0.7) +\n    geom_ribbon(data = high, aes(ymin = 0, ymax = null, fill = \"Type I Error\"),  alpha = 0.7) +\n    geom_line(aes(y = alt,  color = \"Alternative\")) +\n    geom_line(aes(y = null, color = \"Null\")) +\n    geom_hline(yintercept = 0) +\n    scale_color_manual(\n      name = NULL,\n      values = c(\n        Alternative = \"#FF0000\",\n        Null = \"#000000\"\n      )\n    ) + \n    scale_fill_manual(\n      name = NULL,\n      values = c(\"Power\"         = \"#4747bb\",\n                \"Type I Error\"  = \"#cd3737\",\n                \"Type II Error\" = \"#D3D3D3\")\n    ) +\n    guides(color = guide_legend(order = 1),\n          fill   = guide_legend(order = 2)) +\n    labs(\n      title = sprintf(\"f = %.2f; k = %d; n = %d; N = %d\", f, k, n, N),\n      x = \"F\", y = \"Density\"\n    ) +\n    theme_bw()\n  }\n\n(power_plot(n=40,k=5,f=.25,alpha=.05))\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-pdf/unnamed-chunk-5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n\n## Part b\nThe project was funded by several agencies. Suppose that a funding agency suggested funding limiting the researchers to $N=150$. Evaluate this suggestion in the context of the ANOVA. Would that be large enough to be adequately powered?\n\nCompute the non-centrality parameter \n$$\\lambda = k \\cdot n \\cdot f^2$$\nand use the non-central $F$ distribution to compute the power under $H_a$ for Cohen's $f = 0.25$.  Calculate the statistical power achieved under this budget constraint. Note that the best answers will have a corresponding graphical display.\n\n**Solution**\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npow = pwr::pwr.anova.test(\n  k = 5,\n  n = 30,\n  f = .25,\n  sig.level = .05\n)\n(pow$power)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.6675964\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nGiven the standard power target of $.8$, the experiment with only $150$ total participants would be underpowered.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\npower_plot(n=30,k=5,f=.25,alpha=.05)\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## Part c\nIn the article the researchers state:\n\n> *However, the statistical power was not sufficient to allow an accurate discrimination of no to moderate stages of hepatic fibrosis (F0–F2) from severe fibrosis and cirrhosis (F3 and F4).*\n\nThe European Association for the Study of the Liver (EASL) provides treatment recommendations based on these stages. \n\n* Stages 0-1: Treatment is deferred with regularly assessment\n* Stage 2: Treatment is justified for those in stage 2\n* Stage 3-4: Treatment is a priority for those in stages\n\nSuppose the researcher wanted to perform a follow-up test where they want to ensure adequate power not just for the overall ANOVA $F$-test, but specifically to detect a pairwise differences between stages 1 and 2. Explain why the sample size computed in Part a may not be enough and use `PMCMRplus::power.tukey.test()` to compute a sample size that attains adequate power. \n\n**Note**: The researchers would have had to do this *a priori*. Because we aren't medical experts, you can use sample estimates using the original data.\n\\begin{align*}\n  n & = \\text{answer from part a}\\\\\n  \\mu_{\\Delta} & = 0.25 \\\\ \n  \\sigma^2_{\\text{pooled}} & = \\frac{(176-1)0.85^2 + (135-1)0.84^2}{176+135-2} = 0.7152\\\\\n  \\sigma_{\\text{within}}= 0.77\n\\end{align*}\n\n**Solution**\n\nIntuitively, the probability of detecting some difference between an arbitrary number of means is greater than the probability of detecting a specific difference between two means. This follows from the idea that finding any difference in an arbitrary number of means is equivalent to multiple pairwise comparisons, while finding the difference between two specific means is only one such comparison.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nn = 40\npower = 0\nwhile (power < .8) {\n  power = PMCMRplus::power.tukey.test(\n    n = n,\n    groups = 2,\n    delta = .25,\n    within.var = .77^2\n  )$power\n  n = n + 1\n}\n(n - 1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 150\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nGiven two groups, assuming a true difference in means of $.25$ and within group variance of $.5929$, the minimum number of observations per group to be sufficiently powered $(.8)$ is $150$. We can't immediately expand this to the total sample size, as if the researchers were interested in pairwise comparisons between other groups, the within group variance and true difference in means might vary.\n\n\n\n## Part d\nHow does the answer to Part c change if they wanted to have adequate power for *all* pairwise comparisons? Use `Superpower::ANOVA_design()` to set up the ANOVA set up.\n\n**Note**: Use design \"5b\" and the following.\n\\begin{align*}\n  \\boldsymbol{\\mu} &= \\{2.92, 3.11, 3.36, 4.04, 4.35\\}\\\\\n  \\sigma^2 &= \\frac{(97-1)0.87^2 + (176-1)0.85^2 + (135-1)0.84^2 + (67-1)1.00^2 + (67-1)0.90^2}{97+176+135+67+67-5} = 0.80\n\\end{align*}\n\nCompute the power of the researcher's design (part a) using `Superpower::ANOVA_power()`. If the researchers were able to oversample by double, a common approach to addressing this issue, would their power be at least 80% for all pariwise comparisons?\n\n**Note**: This code can take a minute. You may want to set `cache: true` in your `R` chunk yaml header. You will also see more power because the actual effect size was 0.55.\n\n**Solution** \n\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nog = 40\ndoubled = 80\ndesign.og = Superpower::ANOVA_design(\n  design = \"5b\",\n  n = og,\n  mu = c(2.92,3.11,3.36,4.04,4.35),\n  sd = .8944,\n  plot = FALSE\n)\n\ndesign.doubled = Superpower::ANOVA_design(\n  design = \"5b\",\n  n = doubled,\n  mu = c(2.92,3.11,3.36,4.04,4.35),\n  sd = .8944,\n  plot = FALSE\n)\n\npower.og = min(Superpower::ANOVA_power(design_result = design.og, verbose=FALSE)$pc_results$power)\npower.doubled = min(Superpower::ANOVA_power(design_result = design.doubled, verbose=FALSE)$pc_results$power)\n(power.og)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 15.2\n```\n\n\n:::\n\n```{.r .cell-code}\n(power.doubled)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 25.6\n```\n\n\n:::\n:::\n\n\n \\normalsize\nGiven the total sample size of $200$ computed in part a, even after doubling the total sample size to $400$, the test would still be very underpowered.\n\n# Question 3: An Application\n@Yang23 investigate whether low-dose nicotine can counteract age-related metabolic decline. The proposed mechanism is through $\\text{NAD}^+$, which is a chemical compound essential for metabolic energy production. The idea is that low-dose nicotine could help improve and/or maintain the recycling of $\\text{NAD}^+$ by activating the salvage enzyme NAMPT via SIRT1. This could, in turn, restore $\\text{NAD}^+$ homeostasis, which is the biological balance maintained within a cell between the production, recycling, and degradation of nicotinamide adenine dinucleotide ($\\text{NAD}^+$).\n\n**Note:** It is low-dose nicotine. Cigarette smoking delivers massive doses of nicotine along with other harmful chemicals. This is not an endorsement for smoking. \n\nMale mice across distinct life stages -- 2, 6, and 16 months -- were categorized to evaluate natural, age-dependent metabolic and enzymatic shifts in two conditions.\n\n* Treatment: low-dose nicotine (administered in drinking water)\n* Control: no-dose placebo (administered in drinking water)\n\nThe researchers then aimed to compare treatment against control in the following samples:\n\n* 2 months old, control\n* 6 months old, control\n* 16 months old, control\n* 16 months old, treatment\n\nUsing PET imaging, the researchers measured age-induced inflammatory glucose hypermetabolism ($\\text{SUV}_{\\text{max}}$). They want to show that this quantity increases with age and those in the nicotine group saw levels comparable to younger mice.\n\n| Replicate | 2M | 6M | 16M | 16M, Treatment |\n|:---|:---:|:---:|:---:|:---:|\n| 1 | 1.48969 | 4.36000 | 7.30182 | 4.69304 |\n| 2 | 1.30168 | 4.28807 | 7.12416 | 2.51326 |\n| 3 | 1.30620 | 3.64184 | 8.28764 | 2.38019 |\n\n: $\\text{SUV}_{\\text{max}}$ measurements in the heart across age and treatment groups {#tbl-SUV}\n\n## Part a\nState the null ($H_0$) and alternative ($H_a$) hypotheses for the omnibus test.\n\n**Solution**\n\n$H_o: \\mu_{2,C} = \\mu_{6,C} = \\mu_{16,C} = \\mu_{16,E}$\n\n$H_a:$ At least one mean is different\n\n\n## Part b\nPerform some exploratory data analysis to provide empirical information about the researchers question.\n\n**Solution**\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngroups = factor(c(\"2M(C)\",\"6M(C)\",\"16M(C)\",\"16M(E)\"),level = c(\"2M(C)\",\"6M(C)\",\"16M(C)\",\"16M(E)\"))\n\ndat = tibble(\n  x = c(1.48969,1.30168,1.30620,4.36,4.22807,3.64184,7.30182,7.12416,8.28764,4.69304,2.51326,2.38019),\n  groups = rep(groups, each = 3)\n)\n\nsummary = dat |>\n  group_by(groups) |>\n  summarise(\n    n        = n(),\n    mean     = mean(x),\n    median   = median(x),\n    sd       = sd(x),\n    skewness = e1071::skewness(x),\n    .groups  = \"drop\"\n  )\n```\n:::\n\n\n \\normalsize\n\n \\normalsize\n\n\n::: {#tbl-eda .cell tbl-cap='Summary Statistics'}\n\n```{.r .cell-code}\nsummary_table = summary |> knitr::kable(digits=2)\n\n(summary_table)\n```\n\n::: {.cell-output-display}\n\n\n|groups |  n| mean| median|   sd| skewness|\n|:------|--:|----:|------:|----:|--------:|\n|2M(C)  |  3| 1.37|   1.31| 0.11|     0.38|\n|6M(C)  |  3| 4.08|   4.23| 0.38|    -0.33|\n|16M(C) |  3| 7.57|   7.30| 0.63|     0.35|\n|16M(E) |  3| 3.20|   2.51| 1.30|     0.38|\n\n\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot_dat = summary |>\n  mutate(se = sd / sqrt(n))\n\nggplot(plot_dat, aes(x = groups, y = mean)) +\n  geom_col(fill = \"grey70\", colour = \"black\", width = 0.65) +\n  geom_errorbar(aes(ymin = mean - se, ymax = mean + se), width = 0.15) +\n  geom_point(data = dat, aes(x = groups, y = x),\n             shape = 21, fill = \"white\", size = 2) +\n  labs(x = \"Condition\", y = \"Mean (± 1 SE)\") +\n  scale_x_discrete(limits = groups) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](HW2_files/figure-pdf/fig-mice-eda-1.pdf){#fig-mice-eda fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n## Part c\nPerform and report the results of the omnibus test. Make sure to evaluate the conditions for using the method you choose.\n\n**Solution**\n\nGiven the observed differences in standard deviation, and the plasible enough mechanistic argument that we observe more variation in populations as they age due to compounding effects of aging over time, the violation of constant variation across groups for Anova is potentially violated, and as such we proceed with Welch's Anova. Since different mice are used at each age, there's no concern of dependence across time, and otherwise we expect individual mice to be independent. Lab mice are also genetically engineered to be highly similar, so representativeness with respect to the population of lab mice is also reasonable. As mentioned in the paper, the sample size of $3$ per group is too small to make any argument for or against normality. This is a big concern, but it's also plausible that researchers with domain specific knowledge have some good reasons to suggest that the distribution of these markers should be approximately normal. Thankfully, ANOVA and Welch's ANOVA are somewhat robust to only a violation of normality, so we are not greatly concerned for the validity of the subsequent analysis.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwanova.test = rstatix::welch_anova_test(dat, x ~ groups)\n(wanova.test$p)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.000658\n```\n\n\n:::\n:::\n\n\n \\normalsize\n\nGiven a p-value of $.000658$, we report statistically significant support for the alternative hypothesis.\n\n## Part d\nConduct post-hoc pairwise comparisons to determine if age-induced inflammatory glucose hypermetabolism increase with age and whether low-dose nicotine reduces age-induced inflammatory glucose hypermetabolism. \n\n**Solution**\n\nGiven that our choice of omnibus depended on the violation of the assumption of equal variance, we additionally perform post-hoc testing with the Games-Howell test as it continues this relaxation. Analytically this manifests as a modification of the standard error estimate used in the construction of Tukey's HSD.\n\n\n \\normalsize\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGH.post.hoc = rstatix::games_howell_test(dat, x ~ groups)\nord = c(\n  \"6M(C) - 2M(C)\",\n  \"16M(C) - 2M(C)\",\n  \"16M(C) - 6M(C)\",\n  \"16M(E) - 2M(C)\",\n  \"16M(E) - 6M(C)\",\n  \"16M(E) - 16M(C)\"\n)\n\nplot_dat = GH.post.hoc\nplot_dat$comparison = paste(plot_dat$group2, \"-\", plot_dat$group1)\nplot_dat$comparison = factor(plot_dat$comparison, levels = rev(ord))\n\nggplot(plot_dat, aes(x = estimate, y = comparison)) +\n  geom_vline(xintercept = 0, linetype = \"dashed\") +\n  geom_errorbarh(aes(xmin = conf.low, xmax = conf.high), height = 0) +\n  geom_point(size = 3) +\n  labs(\n    title = \"Pairwise Games Howell Confidence Intervals\",\n    x = \"Estimated Difference\",\n    y = \"Comparison\"\n  ) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![Post-Hoc Confidence Intervals](HW2_files/figure-pdf/fig-post-hoc-1.pdf){#fig-post-hoc fig-pos='H'}\n:::\n:::\n\n\n \\normalsize\n\n\n \\normalsize\n\n\n::: {#tbl-effect-size .cell tbl-cap='Post-Hoc Effect Sizes'}\n\n```{.r .cell-code}\neffect.sizes = rstatix::cohens_d(dat, x ~ groups, var.equal = FALSE, hedges.correction = TRUE)\n\nes.table = effect.sizes |>\n  mutate(\n    comparison = paste(group2, \"-\", group1),\n    g          = -effsize\n  ) |>\n  arrange(match(comparison, ord)) |>\n  select(comparison, g) |>\n  knitr::kable(digits = 3, col.names = c(\"Comparison\", \"Hedges' g\"))\n\n(es.table)\n```\n\n::: {.cell-output-display}\n\n\n|Comparison      | Hedges' g|\n|:---------------|---------:|\n|6M(C) - 2M(C)   |     7.724|\n|16M(C) - 2M(C)  |    11.041|\n|16M(C) - 6M(C)  |     5.385|\n|16M(E) - 2M(C)  |     1.589|\n|16M(E) - 6M(C)  |    -0.736|\n|16M(E) - 16M(C) |    -3.433|\n\n\n:::\n:::\n\n\n \\normalsize\n\nAs seen in @fig-post-hoc, we have statistically significant support for the difference in biomarker across control ages. The positive sign of these differences and the relative magnitudes are consistent with the idea that the marker is present at higher levels as mice age. With respect to the experimental results, exposure to the experimental condition leads to no statistically significant differences between $16$ month old mice and both $2$ and $6$ month old mice, as well as significant differences from the control population of $16$ month old mice. This is a significant evidence suggesting that the experimental condition makes mice younger than their age-peers, and statistically indistinguishable from younger mice with respect to the biomarker of interest. As shown in @tbl-effect-size, the effect size is large for all comparisons except for the difference between the 16 month old experimental condition and the 6 month old control condition, in which the effect size is medium.\n\n\n## Part e\nWrite a short paragraph directly addressing the researcher's hypothesis using your work in (a)-(d).\n\nThe researchers in @Yang23 are interested in whether nicotine can combat age related metabolic decline. They observe a metabolic biomarker that is known to increase in age across 3 populations of mice: 2 month, 6 month, and 16 month old. The researcher assign the experimental condition to one population of 16 month old mice, and another is left as a control. Using the collected data on the 4 groups of 3 mice per group, we perform Welch's ANOVA and post-hoc Games-Howell tests. We presume independence of samples and population representativeness given limited domain-specific knowledge. We acknowledge the sample size is insufficient to justify normality give observations of the sample data. We use Welch's anova and Games-Howell tests specifically because of evidence of violations of the assumption of constant variance across samples as shown in @fig-mice-eda. We report significant support for our omnibus analysis, suggesting there exists some difference across means. We follow up with post-hoc testing as seen in @fig-post-hoc showing that while 16 month old mice in the control population have a discernibly higher lever of the biomarker of interest, 16 month old mice in the experimental population are not statistically discernible from younger mice, and have a discernibly lower level of the biomarker from the 16 month old mice in the control population. Using our effect size results in @tbl-effect-size, two differences between the experimental and control conditions had a large effect size, while one difference had a medium effect size.  Given the statistical analysis, we conclude that the data offers evidence in favor of the affirmative answer to the broader research question proposed in @Yang23\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}